### PR TITLE
Fix: disable wipeStorage to prevent losing data for Redis adapter

### PR DESCRIPTION
**Pull request by asanikovich**
I offer to disable `wipeStorage` to prevent losing data for `Redis` adapter:

I use in  an app `Redis` storage for CollectorRegistry:
```php
$this->app->scoped(CollectorRegistry::class, function () {
            $client = $this->app->get('redis.connection')->client();

            return new CollectorRegistry(RedisStorage::fromExistingConnection($client), false);
});
```

Default `RenderCollectorsAction` flush each time storage which loses data for `Redis` adapter.

### CODE REVIEW

**Comment by asanikovich** [comment]
@fideloper @freekmurze

**Comment by freekmurze** [comment]
Could you explain why this change is needed?

These change break the tests and real world usage.

**Comment by asanikovich** [comment]
@freekmurze 
I use Redis as storage for CollectorRegistry with some custom extra metrics.
And `wipeStorage` will erase Redis storage, which is unsuitable for me.

**Comment by freekmurze** [comment]
I'm going to leave it like it is for now.

You can specify your own action class in the config file 👍

**Pull request closed without merging**
